name: nrc_app
description: "Nihon Retro Computers - Retro computer e-commerce app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.3.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  flutter_stripe: ^10.0.0
  webview_flutter: ^4.4.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - .env
  
  generate: true # Enable generation of localized values
